name: RSS Aggregator
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  aggregate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install feedparser feedgen pytz
    
    - name: Run aggregator
      run: python aggregate.py
    
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add feed.xml
        git diff --quiet && git diff --staged --quiet || git commit -m "Update aggregated feed $(date +'%Y-%m-%d %H:%M')"
        git push
